---
title: "CodeBook"
author: "Elisa Villar"
date: "30/12/2021"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The run_analysis.R script performs the data preparation and then followed by the 5 steps required as described in the course project’s definition.

## Download the dataset
 * Dataset downloaded and extracted under the folder called UCI HAR Dataset

## Assign each data to variables

* features <- features.txt : 561 rows, 2 columns
* activities <- activity_labels.txt : 6 rows, 2 columns
* subject_test <- test/subject_test.txt : 2947 rows, 1 column
* x_test <- test/X_test.txt : 2947 rows, 561 columns
* y_test <- test/y_test.txt : 2947 rows, 1 columns
* subject_train <- test/subject_train.txt : 7352 rows, 1 column
* x_train <- test/X_train.txt : 7352 rows, 561 columns
* y_train <- test/y_train.txt : 7352 rows, 1 columns

## Merges the training and the test sets to create one data set

x (10299 rows, 561 columns) is created by merging x_train and x_test using rbind() function
y (10299 rows, 1 column) is created by merging y_train and y_test using rbind() function
subject (10299 rows, 1 column) is created by merging subject_train and subject_test using rbind() function.
all_in_one (10299 rows, 563 column) is created by merging dubject, x and y using cbind() function.

## Extracts only the measurements on the mean and standard deviation for each measurement

activity_names (10299 rows, 88 columns) is created by subsetting all_in_one, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement.

## Uses descriptive activity names to name the activities in the data set

Entire numbers in code column of the activity_names replaced with corresponding activity taken from second column of the activities variable

## Appropriately labels the data set with descriptive variable names

code column in activity_names renamed into activities: 
* All Acc in column’s name replaced by Accelerometer
* All Gyro in column’s name replaced by Gyroscope
* All BodyBody in column’s name replaced by Body
* All Mag in column’s name replaced by Magnitude
* All start with character f in column’s name replaced by Frequency
* All start with character t in column’s name replaced by Time

## From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject

tidy_data (180 rows, 88 columns) is created by sumarizing activity_names taking the means of each variable for each activity and each subject, after groupped by subject and activity.
